<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ANANDASBEASTLAPTOP" name="test_retryReport" tests="3" failures="3" timestamp="26 May 2024 12:38:01 GMT" time="0.02" errors="0">
  <testcase name="method1_Fail" time="0.0" classname="reTry_FailedTestCases.Using_IAnnotationTransformer">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at reTry_FailedTestCases.Using_IAnnotationTransformer.method1_Fail(Using_IAnnotationTransformer.java:12)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- method1_Fail -->
  <testcase name="method1_Fail" time="0.016" classname="reTry_FailedTestCases.Using_IAnnotationTransformer">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at reTry_FailedTestCases.Using_IAnnotationTransformer.method1_Fail(Using_IAnnotationTransformer.java:12)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- method1_Fail -->
  <testcase name="method1_Fail" time="0.0" classname="reTry_FailedTestCases.Using_IAnnotationTransformer">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at reTry_FailedTestCases.Using_IAnnotationTransformer.method1_Fail(Using_IAnnotationTransformer.java:12)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- method1_Fail -->
</testsuite> <!-- test_retryReport -->
