<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ANANDASBEASTLAPTOP" name="Default test(failed)" tests="3" failures="3" timestamp="26 May 2024 00:44:53 GMT" time="0.033" errors="0">
  <testcase name="method1_Fail" time="0.016" classname="reTry_FailedTestCases.Retry_using_IRetryAnalyzer">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at reTry_FailedTestCases.Retry_using_IRetryAnalyzer.method1_Fail(Retry_using_IRetryAnalyzer.java:14)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- method1_Fail -->
  <testcase name="method1_Fail" time="0.0" classname="reTry_FailedTestCases.Retry_using_IRetryAnalyzer">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at reTry_FailedTestCases.Retry_using_IRetryAnalyzer.method1_Fail(Retry_using_IRetryAnalyzer.java:14)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- method1_Fail -->
  <testcase name="method1_Fail" time="0.009" classname="reTry_FailedTestCases.Retry_using_IRetryAnalyzer">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at reTry_FailedTestCases.Retry_using_IRetryAnalyzer.method1_Fail(Retry_using_IRetryAnalyzer.java:14)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- method1_Fail -->
</testsuite> <!-- Default test(failed) -->
